version: "3.7"

services:
  API:
    image: 'auth-app-server.jar'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/<database_name>
      - SPRING_DATASOURCE_USERNAME=<username>
      - SPRING_DATASOURCE_PASSWORD=<password>
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=<database_password>
      - POSTGRES_USER=<database_user>
      - POSTGRES_DB=<database_name>
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5